import { beforeAll, describe, expect, it } from "vitest";
import { bootstrapSettings } from "../src/core/settings-bootstrap.js";
import { SettingsManager } from "../src/core/settings-manager.js";

describe("Editing settings", () => {
	beforeAll(() => {
		bootstrapSettings();
	});

	describe("edit mode defaults", () => {
		it("should return default values for edit mode", () => {
			const manager = SettingsManager.inMemory();

			expect(manager.get("edit.mode")).toBe("hashline");
			expect(manager.get("edit.fuzzyMatch")).toBe(true);
			expect(manager.get("edit.fuzzyThreshold")).toBe(0.95);
			expect(manager.get("edit.streamingAbort")).toBe(false);
			expect(manager.get("edit.blockAutoGenerated")).toBe(true);
		});
	});

	describe("read option defaults", () => {
		it("should return default values for read options", () => {
			const manager = SettingsManager.inMemory();

			expect(manager.get("readLineNumbers")).toBe(false);
			expect(manager.get("readHashLines")).toBe(true);
			expect(manager.get("read.defaultLimit")).toBe(300);
			expect(manager.get("read.prosechunks")).toBe(false);
			expect(manager.get("read.explorechunks")).toBe(false);
			expect(manager.get("read.anchorstyle")).toBe("full");
		});
	});

	describe("bash interceptor defaults", () => {
		it("should return default value for bash interceptor", () => {
			const manager = SettingsManager.inMemory();

			expect(manager.get("bashInterceptor.enabled")).toBe(false);
		});
	});

	describe("python defaults", () => {
		it("should return default values for python execution", () => {
			const manager = SettingsManager.inMemory();

			expect(manager.get("python.toolMode")).toBe("both");
			expect(manager.get("python.kernelMode")).toBe("session");
			expect(manager.get("python.sharedGateway")).toBe(true);
		});
	});

	describe("overrides", () => {
		it("should allow switching edit mode", () => {
			const manager = SettingsManager.inMemory({
				edit: { mode: "patch" },
			});
			expect(manager.get("edit.mode")).toBe("patch");
		});

		it("should allow configuring fuzzy matching", () => {
			const manager = SettingsManager.inMemory({
				edit: { fuzzyMatch: false, fuzzyThreshold: 0.8 },
			});
			expect(manager.get("edit.fuzzyMatch")).toBe(false);
			expect(manager.get("edit.fuzzyThreshold")).toBe(0.8);
		});

		it("should allow enabling streaming abort and disabling block auto-generated", () => {
			const manager = SettingsManager.inMemory({
				edit: { streamingAbort: true, blockAutoGenerated: false },
			});
			expect(manager.get("edit.streamingAbort")).toBe(true);
			expect(manager.get("edit.blockAutoGenerated")).toBe(false);
		});

		it("should allow configuring read limits", () => {
			const manager = SettingsManager.inMemory({
				read: { defaultLimit: 100 },
			});
			expect(manager.get("read.defaultLimit")).toBe(100);
		});

		it("should allow enabling prose and explore chunks", () => {
			const manager = SettingsManager.inMemory({
				read: { prosechunks: true, explorechunks: true, anchorstyle: "checksum" },
			});
			expect(manager.get("read.prosechunks")).toBe(true);
			expect(manager.get("read.explorechunks")).toBe(true);
			expect(manager.get("read.anchorstyle")).toBe("checksum");
		});

		it("should allow enabling bash interceptor", () => {
			const manager = SettingsManager.inMemory({
				bashInterceptor: { enabled: true },
			});
			expect(manager.get("bashInterceptor.enabled")).toBe(true);
		});

		it("should allow configuring python execution", () => {
			const manager = SettingsManager.inMemory({
				python: {
					toolMode: "script",
					kernelMode: "ephemeral",
					sharedGateway: false,
				},
			});
			expect(manager.get("python.toolMode")).toBe("script");
			expect(manager.get("python.kernelMode")).toBe("ephemeral");
			expect(manager.get("python.sharedGateway")).toBe(false);
		});
	});
});
