import { existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { createEditToolDefinition } from "../src/core/tools/edit.js";

describe("edit.blockAutoGenerated", () => {
	let testDir: string;

	beforeEach(() => {
		testDir = join(tmpdir(), `edit-block-test-${Date.now()}`);
		mkdirSync(testDir, { recursive: true });
	});

	afterEach(() => {
		if (testDir && existsSync(testDir)) {
			rmSync(testDir, { recursive: true, force: true });
		}
	});

	it("blocks editing of auto-generated files when enabled", async () => {
		const file = join(testDir, "generated.ts");
		writeFileSync(file, "// Code generated by protoc. DO NOT EDIT.\nconst x = 1;");

		const tool = createEditToolDefinition(testDir, { blockAutoGenerated: true });
		await expect(
			tool.execute(
				"test",
				{
					path: "generated.ts",
					edits: [{ oldText: "const x = 1", newText: "const x = 2" }],
				},
				undefined,
				undefined,
				{} as any,
			),
		).rejects.toThrow("auto-generated files is blocked");
	});

	it("allows editing of auto-generated files when disabled", async () => {
		const file = join(testDir, "generated.ts");
		writeFileSync(file, "// Code generated by protoc. DO NOT EDIT.\nconst x = 1;");

		const tool = createEditToolDefinition(testDir, { blockAutoGenerated: false });
		const result = await tool.execute(
			"test",
			{
				path: "generated.ts",
				edits: [{ oldText: "const x = 1", newText: "const x = 2" }],
			},
			undefined,
			undefined,
			{} as any,
		);
		const text = result.content
			.filter((c: any) => c.type === "text")
			.map((c: any) => c.text)
			.join("\n");
		expect(text).toContain("Successfully replaced");
	});

	it("allows editing of normal files by default", async () => {
		const file = join(testDir, "normal.ts");
		writeFileSync(file, "const x = 1;");

		const tool = createEditToolDefinition(testDir);
		const result = await tool.execute(
			"test",
			{
				path: "normal.ts",
				edits: [{ oldText: "const x = 1", newText: "const x = 2" }],
			},
			undefined,
			undefined,
			{} as any,
		);
		const text = result.content
			.filter((c: any) => c.type === "text")
			.map((c: any) => c.text)
			.join("\n");
		expect(text).toContain("Successfully replaced");
	});
});
