/**
 * Auto-generated files guard - warns about editing generated files
 */

import { readFile } from "node:fs/promises";
import type { HookContext, ToolEvent } from "@mariozechner/pi-coding-agent";
import { getSetting } from "../../settings/lib/settings-store.js";
import { BaseGuard } from "../lib/base-guard.js";
import type { GuardResult } from "../lib/types.js";

const AUTO_GENERATED_PATTERNS = [
	/^package-lock\.json$/,
	/\.min\.js$/,
	/\.min\.css$/,
	/yarn\.lock$/,
];

const AUTO_GENERATED_MARKERS = [
	"DO NOT EDIT",
	"auto-generated",
	"automatically generated",
	"generated by",
	"@generated",
];

async function isAutoGeneratedFile(filePath: string): Promise<boolean> {
	// Check filename patterns
	for (const pattern of AUTO_GENERATED_PATTERNS) {
		if (pattern.test(filePath)) return true;
	}

	// Check file content for markers
	try {
		const content = await readFile(filePath, "utf-8");
		const firstLine = content.split("\n").slice(0, 10).join("\n").toLowerCase();
		return AUTO_GENERATED_MARKERS.some((marker) => firstLine.includes(marker.toLowerCase()));
	} catch {
		return false;
	}
}

export class AutoGeneratedGuard extends BaseGuard {
	readonly name = "auto-generated-guard";
	readonly toolNames = ["write", "edit"];

	private isEnabled(): boolean {
		const val = getSetting("theFirm.guards.blockAutoGenerated");
		return val !== false; // default true
	}

	async check(event: ToolEvent, ctx: HookContext): Promise<GuardResult | undefined> {
		if (!this.isEnabled()) {
			return this.allow();
		}

		const filePath = (event.input.path as string) ?? "";
		if (!filePath) {
			return this.allow();
		}

		const isAutoGen = await isAutoGeneratedFile(filePath);
		if (!isAutoGen) {
			return this.allow();
		}

		if (!ctx.hasUI) {
			return this.block(`Auto-generated file blocked: ${filePath}`);
		}

		const confirmed = await this.confirm(
			ctx,
			"🛡️ Auto-Generated File",
			`This file appears to be auto-generated:\n\n  ${filePath}\n\nAllow edit?`,
		);

		if (!confirmed) {
			return this.block(`Blocked by user (auto-generated: ${filePath})`);
		}

		return this.allow();
	}
}
