/**
 * Editing settings provider.
 * Edit mode, fuzzy matching, streaming, read options, bash interceptor, python.
 *
 * Upstream comparison (oh-my-pi Editing tab):
 * ┌───────────────────────────────────┬──────────┬──────────────────────────────┐
 * │ Setting                           │ Upstream │ The Firm                     │
 * ├───────────────────────────────────┼──────────┼──────────────────────────────┤
 * │ edit.mode                         │ ✓        │ ✓                            │
 * │ edit.fuzzyMatch                   │ ✓        │ ✓                            │
 * │ edit.fuzzyThreshold               │ ✓ (0.95) │ ✓ (0.95)                     │
 * │ edit.streamingAbort               │ ✓ (false)│ ✓ (false)                    │
 * │ edit.blockAutoGenerated           │ ✓ (true) │ ✓ (true)                     │
 * │ readLineNumbers                   │ ✗        │ ✓ (The Firm unique)          │
 * │ readHashLines                     │ ✗        │ ✓ (The Firm unique)          │
 * │ read.defaultLimit                 │ ✓ (300)  │ ✓ (300)                      │
 * │ read.prosechunks                  │ ✓        │ ✓                            │
 * │ read.explorechunks                │ ✓        │ ✓                            │
 * │ read.anchorstyle                  │ ✓        │ ✓                            │
 * │ lsp.enabled                       │ ✓ (true) │ ✓ (false, code-intel)        │
 * │ lsp.formatOnWrite                 │ ✓        │ ✓ (code-intel)               │
 * │ lsp diagnostics                   │ ✓ (2)    │ ✓ (1 combined, code-intel)   │
 * │ bashInterceptor.enabled           │ ✓        │ ✓                            │
 * │ python.toolMode                   │ ✓        │ ✓                            │
 * │ python.kernelMode                 │ ✓        │ ✓                            │
 * │ python.sharedGateway              │ ✓        │ ✓                            │
 * └───────────────────────────────────┴──────────┴──────────────────────────────┘
 *
 * Conscious divergences:
 * - lsp.enabled defaults to false (The Firm: opt-in) vs true (upstream: opt-out)
 * - lsp diagnostics: The Firm uses a single diagnosticsMode enum vs upstream's
 *   separate diagnosticsOnWrite/diagnosticsOnEdit booleans (more flexible)
 * - readLineNumbers/readHashLines: The Firm unique (upstream uses anchorstyle)
 */
import type { SettingsProvider } from "../../core/settings-registry.js";

export const editingSettings: SettingsProvider = {
	id: "editing",
	settings: {
		// ─── Edit mode ────────────────────────────────────────────
		"edit.mode": {
			type: "enum",
			values: ["replace", "patch", "hashline", "chunk"] as const,
			default: "hashline",
			ui: {
				tab: "editing",
				label: "Edit Mode",
				description: "Select the edit tool variant (replace, patch, hashline, or chunk)",
			},
		},

		"edit.fuzzyMatch": {
			type: "boolean",
			default: true,
			ui: {
				tab: "editing",
				label: "Fuzzy Match",
				description: "Accept high-confidence fuzzy matches for whitespace differences",
			},
		},

		"edit.fuzzyThreshold": {
			type: "number",
			default: 0.95,
			ui: {
				tab: "editing",
				label: "Fuzzy Match Threshold",
				description: "Similarity threshold for fuzzy matches (0.0–1.0)",
				submenu: true,
			},
		},

		"edit.streamingAbort": {
			type: "boolean",
			default: false,
			ui: {
				tab: "editing",
				label: "Abort on Failed Preview",
				description: "Abort streaming edit tool calls when patch preview fails",
			},
		},

		"edit.blockAutoGenerated": {
			type: "boolean",
			default: true,
			ui: {
				tab: "editing",
				label: "Block Auto-Generated Files",
				description: "Prevent editing of files that appear to be auto-generated (protoc, sqlc, swagger, etc.)",
			},
		},

		// ─── Read options ─────────────────────────────────────────
		"readLineNumbers": {
			type: "boolean",
			default: false,
			ui: {
				tab: "editing",
				label: "Line Numbers",
				description: "Prepend line numbers to read tool output by default",
			},
		},

		"readHashLines": {
			type: "boolean",
			default: true,
			ui: {
				tab: "editing",
				label: "Hash Lines",
				description: "Include line hashes in read output for hashline edit mode",
			},
		},

		"read.defaultLimit": {
			type: "number",
			default: 300,
			ui: {
				tab: "editing",
				label: "Default Read Limit",
				description: "Default number of lines returned when agent calls read without a limit",
				submenu: true,
			},
		},

		"read.prosechunks": {
			type: "boolean",
			default: false,
			ui: {
				tab: "editing",
				label: "Prose Chunks",
				description: "Enable chunk rendering for prose files in chunk edit mode",
			},
		},

		"read.explorechunks": {
			type: "boolean",
			default: false,
			ui: {
				tab: "editing",
				label: "Explore Chunks",
				description: "Show chunk tree without checksums for read-only agents like explore",
			},
		},

		"read.anchorstyle": {
			type: "enum",
			values: ["full", "kind", "checksum"] as const,
			default: "full",
			ui: {
				tab: "editing",
				label: "Anchor Style",
				description: "Render chunk anchors with full names, kind prefixes, or checksum-only tags",
				submenu: true,
			},
		},

		// ─── Bash interceptor ─────────────────────────────────────
		"bashInterceptor.enabled": {
			type: "boolean",
			default: false,
			ui: {
				tab: "editing",
				label: "Bash Interceptor",
				description: "Block shell commands that have dedicated tools (find, grep, read, etc.)",
			},
		},

		// ─── Python execution ─────────────────────────────────────
		"python.toolMode": {
			type: "enum",
			values: ["both", "notebook", "script"] as const,
			default: "both",
			ui: {
				tab: "editing",
				label: "Python Tool Mode",
				description: "How Python code is executed (both modes, notebook only, or script only)",
			},
		},

		"python.kernelMode": {
			type: "enum",
			values: ["session", "ephemeral"] as const,
			default: "session",
			ui: {
				tab: "editing",
				label: "Python Kernel Mode",
				description: "Whether to keep IPython kernel alive across calls or create ephemeral kernels",
			},
		},

		"python.sharedGateway": {
			type: "boolean",
			default: true,
			ui: {
				tab: "editing",
				label: "Shared Python Gateway",
				description: "Share IPython kernel gateway across firm instances",
			},
		},
	},
};
