/**
 * settings-schema.ts — Single source of truth for The Firm settings
 *
 * Inspired by oh-my-pi's settings-schema.ts pattern:
 * - Every setting defined once with type, default, and optional UI metadata
 * - Type-safe path-based access via get/set
 * - Declarative: add a `ui` field and it appears in /settings automatically
 *
 * This module has ZERO dependencies on Pi SDK or TUI — pure data + types.
 */

// ═══════════════════════════════════════════════════════════════
// Schema definition types
// ═══════════════════════════════════════════════════════════════

export type SettingTab = "general" | "guards" | "workflows" | "session";

/** Tab display metadata — icon is a themed symbol key */
export type TabMetadata = { label: string; icon: string };

/** Ordered list of tabs for UI rendering */
export const SETTING_TABS: SettingTab[] = ["general", "guards", "workflows", "session"];

/** Tab display metadata */
export const TAB_METADATA: Record<SettingTab, TabMetadata> = {
	general: { label: "General", icon: "⚙" },
	guards: { label: "Guards", icon: "🛡" },
	workflows: { label: "Workflows", icon: "📋" },
	session: { label: "Session", icon: "💾" },
};

// ───────────────────────────────────────────────────────────────
// UI metadata (optional — only settings with `ui` appear in /settings)
// ───────────────────────────────────────────────────────────────

interface UiMetadata {
	tab: SettingTab;
	label: string;
	description: string;
	/** For enum/number/string — show as submenu dropdown vs inline toggle */
	submenu?: boolean;
	/** Condition function name — setting only shown when true */
	condition?: string;
}

// ───────────────────────────────────────────────────────────────
// Type definitions for schema entries
// ───────────────────────────────────────────────────────────────

interface BooleanDef {
	type: "boolean";
	default: boolean;
	ui?: UiMetadata;
}

interface StringDef {
	type: "string";
	default: string | undefined;
	ui?: UiMetadata;
}

interface NumberDef {
	type: "number";
	default: number;
	ui?: UiMetadata;
}

interface EnumDef<T extends readonly string[]> {
	type: "enum";
	values: T;
	default: T[number];
	ui?: UiMetadata;
}

interface ArrayDef<T> {
	type: "array";
	default: T[];
	ui?: UiMetadata;
}

interface RecordDef<T> {
	type: "record";
	default: Record<string, T>;
	ui?: UiMetadata;
}

type SettingDef =
	| BooleanDef
	| StringDef
	| NumberDef
	| EnumDef<readonly string[]>
	| ArrayDef<unknown>
	| RecordDef<unknown>;

// ═══════════════════════════════════════════════════════════════
// Schema definition — The Firm settings
// ═══════════════════════════════════════════════════════════════

export const SETTINGS_SCHEMA = {
	// ── General ──────────────────────────────────────────────
	"theFirm.requireConfirmationBeforeDelete": {
		type: "boolean",
		default: true,
		ui: {
			tab: "general",
			label: "Confirm Before Delete",
			description: "Ask for confirmation before destructive file operations (rm, git clean, etc.)",
		},
	},

	"theFirm.autoSessionName": {
		type: "boolean",
		default: true,
		ui: {
			tab: "general",
			label: "Auto Session Name",
			description: "Automatically generate a descriptive name for each session",
		},
	},

	"theFirm.aceReflection": {
		type: "boolean",
		default: false,
		ui: {
			tab: "general",
			label: "ACE Reflection",
			description: "Enable automatic session reflection and prompt optimization",
		},
	},

	"theFirm.bgProcessTracking": {
		type: "boolean",
		default: true,
		ui: {
			tab: "general",
			label: "Background Process Tracking",
			description: "Track and notify about background processes",
		},
	},

	"theFirm.symbolPreset": {
		type: "enum",
		values: ["emoji", "unicode", "ascii"] as const,
		default: "emoji",
		ui: {
			tab: "general",
			label: "Symbol Preset",
			description: "Icon style used in The Firm UI",
			submenu: true,
		},
	},

	// ── Guards ───────────────────────────────────────────────
	"theFirm.guards.blockProtectedPaths": {
		type: "boolean",
		default: true,
		ui: {
			tab: "guards",
			label: "Block Protected Paths",
			description: "Prevent writes to .env, node_modules/, and other protected paths",
		},
	},

	"theFirm.guards.blockAutoGenerated": {
		type: "boolean",
		default: true,
		ui: {
			tab: "guards",
			label: "Block Auto-Generated Files",
			description: "Prevent editing files that appear to be auto-generated",
		},
	},

	"theFirm.guards.warnDirtyRepo": {
		type: "boolean",
		default: false,
		ui: {
			tab: "guards",
			label: "Warn on Dirty Repo",
			description: "Show a warning when operating on a repo with uncommitted changes",
		},
	},

	// ── Workflows ────────────────────────────────────────────
	"theFirm.workflows.compactionStrategy": {
		type: "enum",
		values: ["context-full", "handoff", "off"] as const,
		default: "context-full",
		ui: {
			tab: "workflows",
			label: "Compaction Strategy",
			description: "How to handle context overflow: in-place, handoff to new session, or disabled",
			submenu: true,
		},
	},

	"theFirm.compaction.thresholdPercent": {
		type: "number",
		default: -1,
		ui: {
			tab: "workflows",
			label: "Compaction Threshold %",
			description: "Percentage of context window before auto-compaction triggers (-1 = use Pi default)",
			submenu: true,
		},
	},

	"theFirm.compaction.thresholdTokens": {
		type: "number",
		default: -1,
		ui: {
			tab: "workflows",
			label: "Compaction Token Limit",
			description: "Fixed token limit for compaction (-1 = use Pi default, overrides percentage if set)",
			submenu: true,
		},
	},

	"theFirm.compaction.handoffSaveToDisk": {
		type: "boolean",
		default: false,
		ui: {
			tab: "workflows",
			label: "Save Handoff Docs",
			description: "Save generated handoff documents to .local/HANDOFF.md",
		},
	},

	"theFirm.compaction.autoContinue": {
		type: "boolean",
		default: true,
		ui: {
			tab: "workflows",
			label: "Auto-Continue",
			description: "Automatically continue after compaction/handoff",
		},
	},

	"theFirm.compaction.reserveTokens": {
		type: "number",
		default: 16384,
		ui: {
			tab: "workflows",
			label: "Reserve Tokens",
			description: "Number of tokens to keep after compaction (higher = more context preserved)",
			submenu: true,
		},
	},

	"theFirm.compaction.keepRecentTokens": {
		type: "number",
		default: 20000,
		ui: {
			tab: "workflows",
			label: "Keep Recent Tokens",
			description: "Always keep the last N tokens of recent conversation",
			submenu: true,
		},
	},

	// ── Session ──────────────────────────────────────────────
	"theFirm.session.autoCompact": {
		type: "boolean",
		default: true,
		ui: {
			tab: "session",
			label: "Auto-Compact",
			description: "Automatically compact context when it gets too large",
		},
	},

	"theFirm.session.saveOnExit": {
		type: "boolean",
		default: true,
		ui: {
			tab: "session",
			label: "Save State on Exit",
			description: "Persist extension state when the session ends",
		},
	},

	// ── Internal settings (no UI) ────────────────────────────
	"theFirm.version": {
		type: "string",
		default: undefined,
	},
} as const;

// ═══════════════════════════════════════════════════════════════
// Type inference
// ═══════════════════════════════════════════════════════════════

type Schema = typeof SETTINGS_SCHEMA;

/** All valid setting paths */
export type SettingPath = keyof Schema;

/** Infer the value type for a setting path */
export type SettingValue<P extends SettingPath> = Schema[P] extends { type: "boolean" }
	? boolean
	: Schema[P] extends { type: "string" }
		? string | undefined
		: Schema[P] extends { type: "number" }
			? number
			: Schema[P] extends { type: "enum"; values: infer V }
				? V extends readonly string[]
					? V[number]
					: never
				: Schema[P] extends { type: "array"; default: infer D }
					? D
					: Schema[P] extends { type: "record"; default: infer D }
						? D
						: never;

// ═══════════════════════════════════════════════════════════════
// Public API — pure functions, no side effects
// ═══════════════════════════════════════════════════════════════

/** Get the default value for a setting path */
export function getDefault<P extends SettingPath>(path: P): SettingValue<P> {
	return SETTINGS_SCHEMA[path].default as SettingValue<P>;
}

/** Check if a path has UI metadata (should appear in settings panel) */
export function hasUi(path: SettingPath): boolean {
	return "ui" in SETTINGS_SCHEMA[path];
}

/** Get UI metadata for a path (undefined if no UI) */
export function getUi(path: SettingPath): UiMetadata | undefined {
	const def = SETTINGS_SCHEMA[path];
	return "ui" in def ? (def.ui as UiMetadata) : undefined;
}

/** Get all paths for a specific tab */
export function getPathsForTab(tab: SettingTab): SettingPath[] {
	return (Object.keys(SETTINGS_SCHEMA) as SettingPath[]).filter((path) => {
		const ui = getUi(path);
		return ui?.tab === tab;
	});
}

/** Get the type of a setting */
export function getType(path: SettingPath): SettingDef["type"] {
	return SETTINGS_SCHEMA[path].type;
}

/** Get enum values for an enum setting */
export function getEnumValues(path: SettingPath): readonly string[] | undefined {
	const def = SETTINGS_SCHEMA[path];
	return "values" in def ? (def.values as readonly string[]) : undefined;
}
