/**
 * The Firm Guards Extension
 *
 * Intercepts tool calls to enforce safety settings:
 *   - requireConfirmationBeforeDelete: confirm before rm/git clean/etc.
 *   - blockProtectedPaths: block writes to .env, node_modules, .git, etc.
 *   - blockAutoGenerated: block edits to package-lock.json, minified files, etc.
 *   - warnDirtyRepo: warn when working in a repo with uncommitted changes
 *
 * All settings read from .pi/settings.json via settings-store.
 */

import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";
import { getSetting } from "../settings/lib/settings-store";

// ═══════════════════════════════════════════════════════════════
// Setting helpers
// ═══════════════════════════════════════════════════════════════

function isDeleteGuardEnabled(): boolean {
	const val = getSetting("theFirm.requireConfirmationBeforeDelete");
	return val === false ? false : true; // default true
}

function isProtectedPathsEnabled(): boolean {
	const val = getSetting("theFirm.guards.blockProtectedPaths");
	return val === false ? false : true; // default true
}

function isAutoGeneratedBlockEnabled(): boolean {
	const val = getSetting("theFirm.guards.blockAutoGenerated");
	return val === false ? false : true; // default true
}

function isWarnDirtyRepoEnabled(): boolean {
	const val = getSetting("theFirm.guards.warnDirtyRepo");
	return val === true; // default false
}

// ═══════════════════════════════════════════════════════════════
// Delete guard
// ═══════════════════════════════════════════════════════════════

const DELETE_PATTERNS = [
	/\brm\s+/,
	/\brmdir\b/,
	/\bunlink\b/,
	/\brsync\b.*--delete/,
	/\bgit\s+clean\b/,
	/\bgit\s+reset\s+--hard/,
	/\bgit\s+checkout\s+\./,
];

// ═══════════════════════════════════════════════════════════════
// Protected paths guard
// ═══════════════════════════════════════════════════════════════

const PROTECTED_PATTERNS = [
	/\.env($|[._])/, // .env, .env.local, .env.production
	/^node_modules\//,
	/\/node_modules\//,
	/^\.git\//,
	/\/\.git\//,
	/\.key$/, // private keys
	/\.pem$/, // certificates
	/credentials/i,
	/\.htpasswd$/,
	/\.ssh\//,
];

// ═══════════════════════════════════════════════════════════════
// Auto-generated guard
// ═══════════════════════════════════════════════════════════════

const AUTO_GENERATED_PATTERNS = [
	/^package-lock\.json$/,
	/\.min\.js$/,
	/\.min\.css$/,
	/yarn\.lock$/,
];

const AUTO_GENERATED_MARKERS = [
	"DO NOT EDIT",
	"auto-generated",
	"automatically generated",
	"generated by",
	"@generated",
];

async function isAutoGeneratedFile(filePath: string): Promise<boolean> {
	// Check filename patterns
	for (const pattern of AUTO_GENERATED_PATTERNS) {
		if (pattern.test(filePath)) return true;
	}

	// Check file content for markers
	try {
		const { readFile } = await import("node:fs/promises");
		const content = await readFile(filePath, "utf-8");
		const firstLine = content.split("\n").slice(0, 10).join("\n").toLowerCase();
		return AUTO_GENERATED_MARKERS.some((marker) => firstLine.includes(marker.toLowerCase()));
	} catch {
		return false;
	}
}

// ═══════════════════════════════════════════════════════════════
// Extension
// ═══════════════════════════════════════════════════════════════

export default function register(pi: ExtensionAPI) {
	// ── Bash tool: delete guard ────────────────────────────
	pi.on("tool_call", async (event, ctx) => {
		if (event.toolName !== "bash") return undefined;
		if (!isDeleteGuardEnabled()) return undefined;

		const command = event.input.command as string;
		const isDelete = DELETE_PATTERNS.some((p) => p.test(command));

		if (!isDelete) return undefined;

		if (!ctx.hasUI) {
			return { block: true, reason: "Delete command blocked (no UI for confirmation)" };
		}

		const confirmed = await ctx.ui.confirm(
			"🗑️ Delete Guard",
			`This command contains a delete operation:\n\n  ${command}\n\nAllow?`,
		);

		if (!confirmed) {
			return { block: true, reason: "Blocked by user (delete guard)" };
		}

		return undefined;
	});

	// ── Write/Edit tools: protected paths guard ────────────
	pi.on("tool_call", async (event, ctx) => {
		if (event.toolName !== "write" && event.toolName !== "edit") return undefined;
		if (!isProtectedPathsEnabled()) return undefined;

		const filePath = (event.input.path as string) ?? "";
		if (!filePath) return undefined;

		const isProtected = PROTECTED_PATTERNS.some((p) => p.test(filePath));
		if (!isProtected) return undefined;

		if (!ctx.hasUI) {
			return { block: true, reason: `Protected path blocked: ${filePath}` };
		}

		const confirmed = await ctx.ui.confirm(
			"🛡️ Protected Path",
			`This file is in a protected path:\n\n  ${filePath}\n\nAllow?`,
		);

		if (!confirmed) {
			return { block: true, reason: `Blocked by user (protected path: ${filePath})` };
		}

		return undefined;
	});

	// ── Write/Edit tools: auto-generated guard ─────────────
	pi.on("tool_call", async (event, ctx) => {
		if (event.toolName !== "write" && event.toolName !== "edit") return undefined;
		if (!isAutoGeneratedBlockEnabled()) return undefined;

		const filePath = (event.input.path as string) ?? "";
		if (!filePath) return undefined;

		const isAutoGen = await isAutoGeneratedFile(filePath);
		if (!isAutoGen) return undefined;

		if (!ctx.hasUI) {
			return { block: true, reason: `Auto-generated file blocked: ${filePath}` };
		}

		const confirmed = await ctx.ui.confirm(
			"🛡️ Auto-Generated File",
			`This file appears to be auto-generated:\n\n  ${filePath}\n\nAllow edit?`,
		);

		if (!confirmed) {
			return { block: true, reason: `Blocked by user (auto-generated: ${filePath})` };
		}

		return undefined;
	});

	// ── Agent start: warn dirty repo ───────────────────────
	pi.on("before_agent_start", async (_event, ctx) => {
		if (!isWarnDirtyRepoEnabled()) return;
		if (!ctx.hasUI) return;

		try {
			const { execSync } = await import("node:child_process");
			const output = execSync("git status --porcelain", {
				cwd: process.cwd(),
				encoding: "utf-8",
				timeout: 5000,
			}).trim();

			if (output) {
				const fileCount = output.split("\n").length;
				ctx.ui.notify(
					`⚠️ Dirty repo: ${fileCount} uncommitted change${fileCount > 1 ? "s" : ""}`,
					"warning",
				);
			}
		} catch {
			// Not a git repo or git not available — skip silently
		}
	});
}
