/**
 * The Firm Guards Extension
 *
 * Intercepts tool calls to enforce safety settings:
 *   - requireConfirmationBeforeDelete: confirm before rm/git clean/etc.
 *   - blockProtectedPaths: block writes to .env, node_modules, .git, etc.
 *   - blockAutoGenerated: block edits to package-lock.json, minified files, etc.
 *
 * All settings read from .pi/settings.json via settings-store.
 */

import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";
import { AutoGeneratedGuard } from "./guards/auto-generated-guard.js";
import { DeleteGuard } from "./guards/delete-guard.js";
import { ProtectedPathsGuard } from "./guards/protected-paths-guard.js";
import type { Guard } from "./lib/types.js";

// Registry of all guards
const GUARD_CONSTRUCTORS = [DeleteGuard, ProtectedPathsGuard, AutoGeneratedGuard];

export default function registerGuards(pi: ExtensionAPI) {
	// Instantiate all guards
	const guards: Guard[] = GUARD_CONSTRUCTORS.map((Constructor) => new Constructor(pi));

	// Register single tool_call handler that delegates to all guards
	pi.on("tool_call", async (event, ctx) => {
		for (const guard of guards) {
			// Skip if this guard doesn't handle this tool
			if (!guard.shouldActivate(event)) {
				continue;
			}

			// Run the guard check
			const result = await guard.check(event, ctx, pi);

			// If guard returned a result (block or allow with modification), return it
			if (result) {
				return result;
			}
		}

		// No guard blocked, allow the tool call
		return undefined;
	});
}

export { BaseGuard } from "./lib/base-guard.js";
export type { Guard, GuardResult } from "./lib/types.js";
// Re-export types and guards for testing
export { AutoGeneratedGuard, DeleteGuard, ProtectedPathsGuard };
